--liquibase formatted sql

--changeset your_name:0002-create-location-table
CREATE TABLE location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    capacity INT NOT NULL
);
